// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQlHDyZrZzndet2_XGZaKVEjaIcM3xw4',
    appId: '1:75877769065:web:7db14a3ec07e6965a267f8',
    messagingSenderId: '75877769065',
    projectId: 'tinkher-ca968',
    authDomain: 'tinkher-ca968.firebaseapp.com',
    storageBucket: 'tinkher-ca968.firebasestorage.app',
    measurementId: 'G-NTJ5RLSGDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO8-ZnZLrWLsb0H4OC9du-LOkcCyU_cSA',
    appId: '1:75877769065:android:890dfaaebc19f237a267f8',
    messagingSenderId: '75877769065',
    projectId: 'tinkher-ca968',
    storageBucket: 'tinkher-ca968.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQlHDyZrZzndet2_XGZaKVEjaIcM3xw4',
    appId: '1:75877769065:web:492893e38165d335a267f8',
    messagingSenderId: '75877769065',
    projectId: 'tinkher-ca968',
    authDomain: 'tinkher-ca968.firebaseapp.com',
    storageBucket: 'tinkher-ca968.firebasestorage.app',
    measurementId: 'G-PJ94QN03HW',
  );
}
